# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20170713_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='veredasCOL',
        ),
    ]
