# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 04:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_delete_veredascol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veredascolombia',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
