# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170421_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='about',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ojovozrecord',
            name='about',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ojovozrecord',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, max_length=255, upload_to='attachments/img/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
