# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170504_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
