# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170504_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimension',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimension',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
