# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_channel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojovozrecord',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
