# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ojovozrecord_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojovozrecord',
            name='audio',
            field=models.FileField(blank=True, upload_to='attachments/audio/%Y/%m/%d/'),
        ),
    ]
