# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 21:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_ojovozrecord_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('hashName', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('isActive', models.BooleanField(default=True)),
                ('attachment_type', models.PositiveSmallIntegerField(choices=[(0, 'image'), (1, 'video'), (2, 'file')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(max_length=40, srid=4326)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_author', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_channel', to='core.Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ojovozrecord',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ojovozrecord',
            name='channel',
        ),
        migrations.DeleteModel(
            name='OjovozRecord',
        ),
        migrations.AddField(
            model_name='attachment',
            name='related_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_record', to='core.Record'),
        ),
    ]
