# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170716_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='name',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'image'), (1, 'video'), (2, 'file'), (3, 'sound')], default=0),
        ),
    ]
