# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170725_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
