# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170814_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
