# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_channel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='channeltag',
            name='related_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_channel', to='core.Channel'),
        ),
    ]
