# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170901_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtag',
            name='record',
        ),
        migrations.RemoveField(
            model_name='recordtag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='RecordTag',
        ),
    ]
