# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170901_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='tags',
        ),
    ]
