# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 03:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_record_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='defaultZoom',
            field=models.SmallIntegerField(default=13),
        ),
        migrations.AddField(
            model_name='channel',
            name='mapCenterLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, max_length=40, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='channel',
            name='maxZoom',
            field=models.SmallIntegerField(default=18),
        ),
    ]
