# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('core', '0031_auto_20170927_0359'),
        ('core', '0030_message_profile'),
    ]

    operations = [
    ]
