# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 21:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20171001_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='mapCenterLocation',
            field=django.contrib.gis.db.models.fields.PointField(max_length=40, srid=4326),
        ),
    ]
